---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: javawebapp
  name: java-controller
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: javawebapp
    spec:
      imagePullSecrets:
      - name: dockersecrepo
      containers:
      - image:  agunuworld/java-web-app                                                              #172.31.9.51:8085/java-web-app:12
        name: javawebapp
        ports:
        - name: javawebapp
          containerPort: 8080  
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: javawebapp
  name: javawebapp
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: javawebapp
